[project]
name = "binance-public-data"
version = "0.1.0"
description = "Binance 公开数据下载脚本"
requires-python = ">=3.11"
dependencies = [
    "pandas",
]

[project.scripts]
bpd-kline = "bpd.cli.kline:main"
bpd-trade = "bpd.cli.trade:main"
bpd-agg-trade = "bpd.cli.agg_trade:main"
bpd-futures-index-price-klines = "bpd.cli.futures_index_price_klines:main"
bpd-futures-mark-price-klines = "bpd.cli.futures_mark_price_klines:main"
bpd-futures-premium-index-klines = "bpd.cli.futures_premium_index_klines:main"

[build-system]
requires = ["uv_build>=0.10.12,<0.11"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "bpd"
module-root = "src"
